### ISSUE TITLE
Errors out when paired with a photon.

### ISSUE THREAD

**Issue by alvinsee** [spark/spark-setup-android#5]
This didn't happen until today, but I'm getting the following exception:

W/DiscoverDeviceActivity﹕ Setup exception thrown:
    io.particle.android.sdk.devicesetup.setupsteps.SetupStepException: Process died while trying to get the device ID
            at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$DiscoverProcessWorker.doTheThing(DiscoverDeviceActivity.java:405)
            at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$4.doInBackground(DiscoverDeviceActivity.java:279)
            at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$4.doInBackground(DiscoverDeviceActivity.java:268)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.ConnectException: failed to connect to /192.168.0.1 (port 5609) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
            at libcore.io.IoBridge.isConnected(IoBridge.java:234)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
            at java.net.Socket.connect(Socket.java:884)
            at io.particle.android.sdk.devicesetup.commands.CommandClient.connect(CommandClient.java:86)
            at io.particle.android.sdk.devicesetup.commands.CommandClient.sendAndMaybeReceive(CommandClient.java:67)
            at io.particle.android.sdk.devicesetup.commands.CommandClient.sendCommandAndReturnResponse(CommandClient.java:54)
            at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$DiscoverProcessWorker.doTheThing(DiscoverDeviceActivity.java:399)
            at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$4.doInBackground(DiscoverDeviceActivity.java:279)
            at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$4.doInBackground(DiscoverDeviceActivity.java:268)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
            at libcore.io.IoBridge.isConnected(IoBridge.java:223)
            at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
            at java.net.Socket.connect(Socket.java:884)
            at io.particle.android.sdk.devicesetup.commands.CommandClient.connect(CommandClient.java:86)
            at io.particle.android.sdk.devicesetup.commands.CommandClient.sendAndMaybeReceive(CommandClient.java:67)
            at io.particle.android.sdk.devicesetup.commands.CommandClient.sendCommandAndReturnResponse(CommandClient.java:54)
            at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$DiscoverProcessWorker.doTheThing(DiscoverDeviceActivity.java:399)
            at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$4.doInBackground(DiscoverDeviceActivity.java:279)
            at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$4.doInBackground(DiscoverDeviceActivity.java:268)
            at android.os.AsyncTask$2.call(AsyncTask.java:295)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
            at java.lang.Thread.run(Thread.java:818)

**Comment by jensck** [comment]
Haven't seen that one before...  there's a new version of the SDK and device setup lib out -- can you reproduce this with the updates?

If so, what Android version is this?

**Comment by jensck** [comment]
No updates for over 1 month, closing.

If this is still an issue, please feel free to re-open!
