### ISSUE TITLE
ParticleDeviceSetupLibrary.initWithSetupOnly(this.getApplicationContext()) fails to get device ID.

### ISSUE THREAD

**Issue by sollematthew** [spark/spark-setup-android#54]
I am attempting to both get a device on a wifi network (which works) and get it's device id returned (which doesn't work). All of the views work correctly visually. However there are some errors thrown in logcat and the `onSetupFailure` method is called instead of `onSetupSuccess`.

My setup code
```java
ParticleDeviceSetupLibrary.initWithSetupOnly(this.mContext);
ParticleDeviceSetupLibrary.startDeviceSetup(this.mContext, MainActivity.class);
```

What I see in the console:
```
io.particle.android.sdk.devicesetup.setupsteps.SetupStepException: Process died while trying to get the device ID
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$DiscoverProcessWorker.doTheThing(DiscoverDeviceActivity.java:440)
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$1.doInBackground(DiscoverDeviceActivity.java:321)
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$1.doInBackground(DiscoverDeviceActivity.java:311)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)
Caused by: java.net.SocketTimeoutException: timeout
at okio.Okio$3.newTimeoutException(Okio.java:210)
at okio.AsyncTimeout.exit(AsyncTimeout.java:288)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:242)
at okio.Buffer.writeAll(Buffer.java:993)
at okio.RealBufferedSource.readUtf8(RealBufferedSource.java:177)
at io.particle.android.sdk.devicesetup.commands.CommandClient.readResponse(CommandClient.java:129)
at io.particle.android.sdk.devicesetup.commands.CommandClient.sendAndMaybeReceive(CommandClient.java:85)
at io.particle.android.sdk.devicesetup.commands.CommandClient.sendCommand(CommandClient.java:62)
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$DiscoverProcessWorker.doTheThing(DiscoverDeviceActivity.java:434)
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$1.doInBackground(DiscoverDeviceActivity.java:321) 
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$1.doInBackground(DiscoverDeviceActivity.java:311) 
at android.os.AsyncTask$2.call(AsyncTask.java:304) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
at java.lang.Thread.run(Thread.java:762) 
Caused by: java.net.SocketException: Socket closed
at java.net.SocketInputStream.socketRead0(Native Method)
at java.net.SocketInputStream.read(SocketInputStream.java:151)
at java.net.SocketInputStream.read(SocketInputStream.java:120)
at okio.Okio$2.read(Okio.java:138)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:238)
at okio.Buffer.writeAll(Buffer.java:993) 
at okio.RealBufferedSource.readUtf8(RealBufferedSource.java:177) 
at io.particle.android.sdk.devicesetup.commands.CommandClient.readResponse(CommandClient.java:129) 
at io.particle.android.sdk.devicesetup.commands.CommandClient.sendAndMaybeReceive(CommandClient.java:85) 
at io.particle.android.sdk.devicesetup.commands.CommandClient.sendCommand(CommandClient.java:62) 
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$DiscoverProcessWorker.doTheThing(DiscoverDeviceActivity.java:434) 
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$1.doInBackground(DiscoverDeviceActivity.java:321) 
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$1.doInBackground(DiscoverDeviceActivity.java:311) 
at android.os.AsyncTask$2.call(AsyncTask.java:304) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
at java.lang.Thread.run(Thread.java:762) 
```

And

```
DiscoverDeviceActivity: Setup exception thrown:                                                                        io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$DeviceAlreadyClaimed: Device already claimed by another user
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$DiscoverProcessWorker.doTheThing(DiscoverDeviceActivity.java:487)
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$1.doInBackground(DiscoverDeviceActivity.java:321)
at io.particle.android.sdk.devicesetup.ui.DiscoverDeviceActivity$1.doInBackground(DiscoverDeviceActivity.java:311)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)
```

And

```
Async: Error calling API: The access token provided is invalid.
o.particle.android.sdk.cloud.ParticleCloudException
at io.particle.android.sdk.cloud.ParticleCloud.getDevice(ParticleCloud.java:690)
at io.particle.android.sdk.cloud.ParticleCloud.getDevice(ParticleCloud.java:425)
at io.particle.android.sdk.devicesetup.ui.SuccessActivity$2.callApi(SuccessActivity.java:216)
at io.particle.android.sdk.devicesetup.ui.SuccessActivity$2.callApi(SuccessActivity.java:213)
at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:111)
at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:79)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)
```

and lastly,

```
io.particle.android.sdk.cloud.ParticleCloudException
at io.particle.android.sdk.cloud.ParticleCloud.getDevices(ParticleCloud.java:346)
at io.particle.android.sdk.devicesetup.ui.ConnectingActivity$ConnectingProcessWorkerTask.lambda$onPostExecute$0(ConnectingActivity.java:273)
at io.particle.android.sdk.devicesetup.ui.ConnectingActivity$ConnectingProcessWorkerTask$$Lambda$1.run(Unknown Source)
at io.particle.android.sdk.utils.EZ$1.doInBackground(EZ.java:46)
at io.particle.android.sdk.utils.EZ$1.doInBackground(EZ.java:42)
at android.os.AsyncTask$2.call(AsyncTask.java:304)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:762)
```

**Comment by CityVibes** [comment]
A non-authenticated user won't have access to device, which is likely cause of your problems since you are using "setup only".
```
ParticleDeviceSetupLibrary.init(this.mContext);
ParticleDeviceSetupLibrary.startDeviceSetup(this.mContext, MainActivity.class);
```
Would end up with `onSetupSuccess`.
