### ISSUE TITLE
"Error calling API : Invalid json" Error during device setup

### ISSUE THREAD

**Issue by sbose78** [spark/spark-setup-android#7]
I was testing out the Android device setup on my Photon when I got the following issue after hitting "Ready". Here are the details to reproduce:

1. Updated app's manifest file.
2.  Called 
```
ParticleDeviceSetupLibrary.init();
ParticleDeviceSetupLibrary.startDeviceSetup(this);
```
in the first activity

3. Got to the screen which said "Time to setup your photon".
4. On tapping the "Ready" button I got the error message on the screen which said "Could not communicate with Photon Cloud.." The corresponding logs were:

```
E/Async   ( 2242): Error calling API: Error: invalid json
E/Async   ( 2242): io.particle.android.sdk.cloud.SparkCloudException
E/Async   ( 2242): 	at io.particle.android.sdk.cloud.SparkCloud.generateClaimCode(SparkCloud.java:342)
E/Async   ( 2242): 	at io.particle.android.sdk.devicesetup.ui.GetReadyActivity$3.callApi(GetReadyActivity.java:104)
E/Async   ( 2242): 	at io.particle.android.sdk.devicesetup.ui.GetReadyActivity$3.callApi(GetReadyActivity.java:101)
E/Async   ( 2242): 	at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:104)
E/Async   ( 2242): 	at io.particle.android.sdk.utils.Async$AsyncApiWorker.doInBackground(Async.java:70)
E/Async   ( 2242): 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
E/Async   ( 2242): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/Async   ( 2242): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/Async   ( 2242): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/Async   ( 2242): 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by jensck** [comment]
What kind of output do you get if you turn on debug logging: https://github.com/spark/spark-sdk-android#logging

**Comment by sbose78** [comment]
Hi, this worked out fine after subsequent tries, and so couldn't reproduce this at my end.
This could be closed.
